{% set name = "openmm-ml" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/openmm/{{ name }}.git
  git_rev: "63aa20a"

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - openmm >=8.0.0
    - python >={{ python_min }}
    - openmm-torch >=1.0
    - torchani >=2.2.2
    - setuptools

test:
  imports:
    - openmmml
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/openmm/openmm-ml
  summary: 'High level API for using machine learning models in OpenMM simulations'
  description: |
    High level API for using machine learning models in OpenMM simulations
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/openmm/openmm-ml
  dev_url: https://github.com/openmm/openmm-ml

extra:
  recipe-maintainers:
    - mikemhenry
    - peastman
