{% set name = "openmm-ml" %}
{% set version = "1.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/openmm/openmm-ml.git
  git_rev: 5b577c2586232d3ac6f41de064d3290619b2a8aa

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - openmm ==8.0.0rc1 # TODO https://conda-forge.org/docs/maintainer/knowledge_base.html#creating-a-pre-release-build once merged into a feedstock, depend on dev for now
    - python >=3.8
    - openmm-torch ==1.0rc1
    - torchani >=2.2.2

test:
  imports:
    - openmmml
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/openmm/openmm-ml
  summary: 'High level API for using machine learning models in OpenMM simulations'
  description: |
    High level API for using machine learning models in OpenMM simulations
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/openmm/openmm-ml
  dev_url: https://github.com/openmm/openmm-ml

extra:
  recipe-maintainers:
    - mikemhenry
    - peastman
