{% set name = "openmm-ml" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openmm/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 444d9a1aad14bd3aa31c6ca51901844aafd25efa791c69398fd394f2ac743949

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - numpy
    - openmm
    - python
    - openmm-torch
    - torchani

test:
  imports:
    - openmmml
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/openmm/openmm-ml
  summary: 'High level API for using machine learning models in OpenMM simulations'
  description: |
    High level API for using machine learning models in OpenMM simulations
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/openmm/openmm-ml
  dev_url: https://github.com/openmm/openmm-ml

extra:
  recipe-maintainers:
    - mikemhenry
    - peastman
